"""Type stubs for _rapcsv Rust extension module."""

from typing import Coroutine, Any, List

class Reader:
    def __init__(self, path: str) -> None: ...
    def read_row(self) -> Coroutine[Any, Any, List[str]]: ...

class Writer:
    def __init__(self, path: str) -> None: ...
    def write_row(self, row: List[str]) -> Coroutine[Any, Any, None]: ...
